name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        cd runner-mb
        pod install --repo-update
      shell: bash
    - uses: ty0x2333/cocoapods-action@master
      with:
        #additional_build_params: -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.0'
        workspace: 'runner-mb.xcworkspace'
        scheme: 'runner-mb'
    - name: Build
      run: swift build -v
    #- name: Run tests
    #  run: swift test -v
